### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by zou-longkun** [momohuang/FlowQA#17]
When I execute python train_QuAC.py,there are errors as following:
Traceback (most recent call last):
  File "train_QuAC.py", line 324, in <module>
    main()
  File "train_QuAC.py", line 175, in main
    model = QAModel(opt, train_embedding)
  File "/home/zoulongkun/project/FlowQA-master/QA_model/model_QuAC.py", line 30, in __init__
    self.network = FlowQA(opt, embedding)
  File "/home/zoulongkun/project/FlowQA-master/QA_model/detail_model.py", line 47, in __init__
    self.CoVe = layers.MTLSTM(opt, embedding)
  File "/home/zoulongkun/project/FlowQA-master/QA_model/layers.py", line 161, in __init__
    state_dict = torch.load(opt['MTLSTM_path'])
  File "/home/zoulongkun/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/zoulongkun/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input

Your help will be highly appreciated!

**Comment by GrassBro** [comment]
I met the same problem with, have you resolved it? @zou-longkun

**Comment by zou-longkun** [comment]
I have resolved it .The reason for this problem is that the file MT-LSTM.path is empty, you need to download this file again. 
You can excute the command line which could be found in download.sh : 
wget https://s3.amazonaws.com/research.metamind.io/cove/wmtlstm-b142a7f2.pth -O glove/MT-LSTM.pth

**Comment by zou-longkun** [comment]
@TinyGrass 
I have resolved it .The reason for this problem is that the file MT-LSTM.path is empty, you need to download this file again.
You can excute the command line which could be found in download.sh :
wget https://s3.amazonaws.com/research.metamind.io/cove/wmtlstm-b142a7f2.pth -O glove/MT-LSTM.pth

**Comment by GrassBro** [comment]
> @TinyGrass
> I have resolved it .The reason for this problem is that the file MT-LSTM.path is empty, you need to download this file again.
> You can excute the command line which could be found in download.sh :
> wget https://s3.amazonaws.com/research.metamind.io/cove/wmtlstm-b142a7f2.pth -O glove/MT-LSTM.pth

Thanks, @zou-longkun .
I resolved it as you said.

**Comment by gmt710** [comment]
@zou-longkun , yes, That's the problem.

**Comment by PaperTigerL** [comment]
> @TinyGrass I have resolved it .The reason for this problem is that the file MT-LSTM.path is empty, you need to download this file again.我已经解决了.出现此问题的原因是文件MT-LSTM.path为空，需要重新下载此文件。 You can excute the command line which could be found in download.sh :您可以在 download.sh 中找到的命令行： wget https://s3.amazonaws.com/research.metamind.io/cove/wmtlstm-b142a7f2.pth -O glove/MT-LSTM.pthwget https://s3.amazonaws.com/research.metamind.io/cove/wmtlstm-b142a7f2.pth -O 手套/MT-LSTM.pth
This XML file does not appear to have any style information associated with it. The document tree is shown below.
this what should gone for me to do? It's seems no data in the website at all.
